config/routes.rb
Rails.application.routes.draw do
  resources :predictions

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: [:show, :edit, :update, :destroy]

  # GET /predictions
  # GET /predictions.json
  def index
    @predictions = Prediction.all
  end

  # GET /predictions/1
  # GET /predictions/1.json
  def show
  end

  # GET /predictions/new
  def new
    @prediction = Prediction.new
  end

  # GET /predictions/1/edit
  def edit
  end

  # POST /predictions
  # POST /predictions.json
  def create
    @prediction = Prediction.new(prediction_params)

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to @prediction, notice: 'Prediction was successfully created.' }
        format.json { render :show, status: :created, location: @prediction }
      else
        format.html { render :new }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1
  # PATCH/PUT /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to @prediction, notice: 'Prediction was successfully updated.' }
        format.json { render :show, status: :ok, location: @prediction }
      else
        format.html { render :edit }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1
  # DELETE /predictions/1.json
  def destroy
    @prediction.destroy
    respond_to do |format|
      format.html { redirect_to predictions_url, notice: 'Prediction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prediction
      @prediction = Prediction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prediction_params
      params.require(:prediction).permit(:first_name, :last_name, :trump_ec_votes, :clinton_ec_votes, :lockin_datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BltpUsElectionSweepstakes2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/predictions/_form.html.erb
<%= form_for(@prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :trump_ec_votes %><br>
    <%= f.number_field :trump_ec_votes %>
  </div>
  <div class="field">
    <%= f.label :clinton_ec_votes %><br>
    <%= f.number_field :clinton_ec_votes %>
  </div>
  <div class="field">
    <%= f.label :lockin_datetime %><br>
    <%= f.datetime_select :lockin_datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/predictions/edit.html.erb
<h1>Editing Prediction</h1>

<%= render 'form' %>

<%= link_to 'Show', @prediction %> |
<%= link_to 'Back', predictions_path %>

app/views/predictions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Predictions</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Trump ec votes</th>
      <th>Clinton ec votes</th>
      <th>Lockin datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @predictions.each do |prediction| %>
      <tr>
        <td><%= prediction.first_name %></td>
        <td><%= prediction.last_name %></td>
        <td><%= prediction.trump_ec_votes %></td>
        <td><%= prediction.clinton_ec_votes %></td>
        <td><%= prediction.lockin_datetime %></td>
        <td><%= link_to 'Show', prediction %></td>
        <td><%= link_to 'Edit', edit_prediction_path(prediction) %></td>
        <td><%= link_to 'Destroy', prediction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prediction', new_prediction_path %>

app/views/predictions/new.html.erb
<h1>New Prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', predictions_path %>

app/views/predictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @prediction.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @prediction.last_name %>
</p>

<p>
  <strong>Trump ec votes:</strong>
  <%= @prediction.trump_ec_votes %>
</p>

<p>
  <strong>Clinton ec votes:</strong>
  <%= @prediction.clinton_ec_votes %>
</p>

<p>
  <strong>Lockin datetime:</strong>
  <%= @prediction.lockin_datetime %>
</p>

<%= link_to 'Edit', edit_prediction_path(@prediction) %> |
<%= link_to 'Back', predictions_path %>